version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: gasdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-gas}
      POSTGRES_USER: ${DB_USER:-gasapp}
      # Use Docker secret for password
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      # Bind to localhost only for security
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-gasapp} -d ${DB_NAME:-gas}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gasapp
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER:-gasapp}
      # App will read password from secret file
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-gas}
    ports:
      - "8000:8000"
    secrets:
      - db_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

secrets:
  db_password:
    external: true
