version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    # If Apple Silicon gives platform issues, uncomment:
    # platform: linux/arm64/v8
    container_name: gasdb
    env_file: .env.db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  db_data:
